apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: auction-svc-dr
  namespace: backend
spec:
  host: auction-clusterip.backend.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
