apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-vs
  namespace: backend
spec:
  hosts:
    - api.nguyenth4nh.id.vn
  gateways:
    - istio-system/main-gateway
  http:
    - route:
        - destination:
            host: gateway-clusterip.backend.svc.cluster.local
            port:
              number: 80
      timeout: 30s
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gateway-dr
  namespace: backend
spec:
  host: gateway-clusterip.backend.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
