apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - app.nguyenth4nh.id.vn
    - api.nguyenth4nh.id.vn
    - id.nguyenth4nh.id.vn
    tls:
      mode: SIMPLE
      credentialName: multi-domain-tls  # ← Đổi thành multi-tls
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - app.nguyenth4nh.id.vn
    - api.nguyenth4nh.id.vn
    - id.nguyenth4nh.id.vn