apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: order-svc-dr
  namespace: backend
spec:
  host: order-clusterip.backend.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

    connectionPool:
      tcp:
        idleTimeout: 2m
      http:
        idleTimeout: 2m
        maxRequestsPerConnection: 100
    tls:
      mode: ISTIO_MUTUAL
