apiVersion: v1
kind: ConfigMap
metadata:
  name: order-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  IdentityServiceUrl: http://identity-clusterip
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=orders
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buyings-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  IdentityServiceUrl: http://identity-clusterip
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deposits-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  IdentityServiceUrl: http://identity-clusterip
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  IdentityServiceUrl: http://identity-clusterip
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80; http://+:7777
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=auctions
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
---
#Dung lenh rollout voi service do de cap nhat thay doi

# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__MongoDbConnection: mongodb://root:mongopw@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
  OrderServiceUrl: http://order-clusterip
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: bid-svc-config
  namespace: default
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
  ConnectionStrings__BidDbConnection: mongodb://root:mongopw@mongo-clusterip
  IdentityServiceUrl: http://identity-clusterip
  GrpcAuction: http://auction-clusterip:7777
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: notify-svc-config
  namespace: default
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbit-clusterip #trung voi cluster ip cua rabbit nham ket noi
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitpw
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-svc-config
  namespace: default
data:
  ASPNETCORE_URLS: http://+:80
  ASPNETCORE_ENVIRONMENT: "K8s"
  ClientApp: https://app.nguyenth4nh.xyz
  IdentityServiceUrl: http://identity-clusterip #Tai vi thieu moi truong cho k8s chi co moi truong cho Docker
  #Nho build lai gateway-svc trong docker truoc khi build k8s
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-svc-config
  namespace: default
data:
  ASPNETCORE_URLS: http://+:80
  IssuerUri: https://id.nguyenth4nh.xyz
  ClientApp: https://app.nguyenth4nh.xyz
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=identity
---
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: webapp-svc-config
  namespace: default
data:
  AUTH_SECRET: "YSM90uLUlNcZqTbv4CTg2qf/X/dYS8+piqW3cgxzOvg="
  ID_URL: https://id.nguyenth4nh.xyz
  AUTH_URL: https://app.nguyenth4nh.xyz
  NOTIFY_URL: http://api.nguyenth4nh.xyz/notifications
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL: http://gateway-clusterip/
  ID_URL_INTERNAL: http://identity-clusterip
---

