# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-svc
  namespace: default
  labels:
    app: identity-svc
spec:
  selector:
    matchLabels:
      app: identity-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-svc
    spec:
      containers:
        - name: identity-svc
          image: nguyenthanh/identity-svc
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: identity-svc-config
          ports:
            - containerPort: 80
              name: web
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
  namespace: default
spec:
  selector:
    app: identity-svc #tro dung container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---

