apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  namespace: backend
  labels:
    app: order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              for i in $(seq 1 30); do
                nc -z postgres-clusterip.backend.svc.cluster.local 5432
                if [ $? -eq 0 ]; then
                  echo "PostgreSQL is ready!"
                  exit 0
                fi
                echo "PostgreSQL not ready, retry $i/30, sleeping 5s..."
                sleep 5
              done
              echo "PostgreSQL still not ready after 30 retries, exiting."
              exit 1
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
            - echo "Waiting for RabbitMQ..."
                for i in $(seq 1 30); do
                  nc -z rabbit-clusterip.backend.svc.cluster.local 5672 && exit 0
                  echo "RabbitMQ not ready ($i/30), sleep 5s"
                  sleep 5
                done
                echo "RabbitMQ not ready after 30 retries"
                exit 1
      containers:
        - name: order-svc
          image: nguyenthanh91ndu/order-svc
          imagePullPolicy: IfNotPresent
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: connString
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
          envFrom:
            - configMapRef:
                name: order-svc-config
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip
  namespace: backend
spec:
  selector:
    app: order-svc
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
