apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: rabbit
            - name: RABBITMQ_DEFAULT_PASS
              value: rabbitpw
          ports:
            - containerPort: 15672
              name: rbmq-mgmt-port
            - containerPort: 5672
              name: rbmq-msg-port
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitdata
      volumes:
        - name: rabbitdata
          persistentVolumeClaim:
            claimName: rabbitmq-claim
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rabbit-clusterip
spec:
  selector:
    app: rabbitmq #map voi ten cua container
  type: ClusterIP
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672 #dia chi trong de cac container giao tiep voi nhau
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-np
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 15672 #dia chi dash board
      targetPort: 15672
      nodePort: 30002
---

