# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
  namespace: default
  labels:
    app: user-svc
spec:
  selector:
    matchLabels:
      app: user-svc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: user-svc
          image: nguyenthanh/user-svc
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: user-svc-config
          ports:
            - containerPort: 80
              name: web

---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip
  namespace: default
spec:
  selector:
    app: user-svc #tro dung container
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: web
---

