apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  namespace: backend
  labels:
    app: order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: order-svc
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      containers:
        - name: order-svc
          image: nguyenthanh91ndu/order-svc
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: connString
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
          envFrom:
            - configMapRef:
                name: order-svc-config
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip
  namespace: backend
spec:
  selector:
    app: order-svc
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
