apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-svc-latest
  namespace: frontend
  labels:
    app: webapp
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: latest
  template:
    metadata:
      labels:
        app: webapp
        version: latest
    spec:
      containers:
        - name: webapp
          image: nguyenthanh91ndu/web-app:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: authSecret
          envFrom:
            - configMapRef:
                name: webapp-svc-config
          ports:
            - containerPort: 3000
              name: web
