name: Application Deployment (GitOps)

on:
  workflow_run:
    workflows: ["CI & Security Scan"]
    types: [completed]
    branches: ["main"]

jobs:
  Update-Manifests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Image Version in YAML
        run: |
          VERSION="v${{ github.run_number }}"
          # Sử dụng sed để cập nhật tag image trong các file k8s
          sed -i "s|image: nguyenthanh91ndu/.*:latest|image: nguyenthanh91ndu/auction-svc:$VERSION|g" infrastructure/k8s/auction-svc.yaml
          # Lặp lại cho các service khác hoặc dùng script thông minh hơn

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update image version to $VERSION [skip ci]"
          git push
